In [80]:
import numpy as np

**Valid Sudoku**

In [81]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [82]:

b = np.sum(s, axis = 1)  # sum of each row
c = np.sum(s, axis = 0)  # sum of each column
print(b)
print(b == 45)

print(c)
print(c == 45)

[45 45 45 45 45 45 45 45 45]
[ True  True  True  True  True  True  True  True  True]
[45 45 45 45 45 45 45 45 45]
[ True  True  True  True  True  True  True  True  True]


In [83]:
# Now need to check sum for each square
a = s[0:3, 0:3]
print(a)
print(np.sum(a))

for i in range(0, 9, 3):
  for j in range(0, 9, 3):
    a = s[i:i + 3, j:j+3]
    sum = np.sum(a)
    if(sum != 45):
      print("False")



[[5 3 4]
 [6 7 2]
 [1 9 8]]
45


In [84]:
def checkValid(s):
  b = np.sum(s, axis = 1)
  c = np.sum(s, axis = 0)
  if(not (b == 45).all() or not (c == 45).all()):
    return False
  for i in range(0, 9, 3):
    for j in range(0, 9, 3):
      a = s[i:i + 3, j:j+3]
      sum = np.sum(a)
      if(sum != 45):
        return False

  return True


In [85]:
print(checkValid(s))

True


**General Questions**

In [86]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [87]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [88]:
#Find the average age of students.
np.mean(data[:, 0])

np.float64(18.4)

In [89]:
#Extract Math marks of all students.
# np.array(data[:, 1])
data[:, 1]

array([85, 92, 76, 65, 90])

In [90]:
#Find the highest Science mark.
np.max(data[:, 2])

np.int64(95)

In [91]:
#Get details of the student who scored more than 90 in Math.
data[data[:, 1] > 90]

array([[19, 92, 88]])

In [92]:
#Increase Math marks of all students by 5.
data[:, 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [93]:
#Find how many students are younger than 19.
len(data[data[:, 0] < 19])

3

In [94]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:, 1:], axis = 0)

array([86.6, 83.2])

In [95]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [97]:
#Replace all Science marks < 75 with 0.
data[:, 2] [data[:, 2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])