In [2]:
import numpy as np

Numpy Indexing and Slicing of Vectors

In [3]:
arr = np.arange(11, 22)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [4]:
arr[2:5]

array([13, 14, 15])

In [5]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [6]:
arr[1,3]

np.int64(9)

In [7]:
slice2D = arr[0:2, 1:3]
slice2D

array([[2, 3],
       [7, 8]])

In [8]:
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [9]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [11]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

**Array Operations**

Arithmetic Operations

In [12]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [13]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [14]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [15]:
a1 // a2

array([0, 0, 0, 0, 0])

In [16]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [17]:
l = [10,20,30,40]
arr = np.array(l)

In [18]:
arr + 10

array([20, 30, 40, 50])

In [19]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow copy

In [21]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a[4:6] *10

array([50, 60])

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a
b = a

In [27]:
b[0] = 90
b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [29]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
A

array([[1, 2],
       [3, 4]])

In [31]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [32]:
A @ B

array([[19, 22],
       [43, 50]])

In [33]:
#Transpose
A.T

array([[1, 3],
       [2, 4]])

# **Array Manipulation**

Stacking Array (You cannot stack two Matrix, you need vector(array) for it)

There are three stack
1. Vertical Stack
2. Horizontal Stack
3. Simple Stack

In [36]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [38]:
np.vstack((a, b)) #Vertical

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
np.hstack((a, b)) #Horizontal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
np.column_stack((a, b)) #Column Stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [46]:
c = np.arange(36).reshape(6,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [48]:
np.hsplit(c, 2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [47]:
np.hsplit(c, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [49]:
np.vsplit(c, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [50]:
np.vsplit(c, 3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [51]:
a = np.vsplit(c, 3)

In [52]:
for i in a:
  print(i)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[24 25 26 27 28 29]
 [30 31 32 33 34 35]]
