In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [5]:
b = [1, 2, 3.2]
b

[1, 2, 3.2]

In [6]:
np.array(b)

array([1. , 2. , 3.2])

2D array

In [7]:
ls = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(ls)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [9]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.zeros((6))
arr

array([0., 0., 0., 0., 0., 0.])

In [11]:
arr = np.zeros((4, 8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

Linear Space (linspace)

In [16]:
arr = np.linspace(1, 5, 10)
arr


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Random(randint)

In [18]:
np.random.randint(10, 20, 10)

array([18, 16, 15, 12, 18, 18, 15, 12, 15, 15])

Array Attributes

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr.shape # since shape is attribute no "()"

(2, 3)

In [25]:
arr.size

6

In [24]:
arr.dtype

dtype('int64')

Array Methods

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(6)

In [28]:
arr.sum()

np.int64(21)

In [29]:
np.sum(arr, axis = 0)

array([5, 7, 9])

Reshaping and Resizing

In [31]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr.reshape(6, 5)  # reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [34]:
arr = arr.reshape(6, 5) # resizing
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])